import { Theme } from './interfaces'; // <<< Import Theme from a new interface file

// --- Bonus Types ---
export interface BonusOption {
  id: string;
  name: string;
  description: string;
  duration: number; // Duration in frames (e.g., 60 frames = 1 second at 60fps)
}

export const BONUS_OPTIONS: BonusOption[] = [
  { id: 'speed_decrease', name: "Chill Out", description: "Slows game speed by 20%", duration: 600 }, // 10 seconds
  { id: 'tiny_player', name: "Shrink Ray", description: "Player becomes 25% smaller", duration: 480 }, // 8 seconds
  { id: 'fewer_obstacles', name: "Clear Skies", description: "Reduces obstacle frequency", duration: 600 }, // 10 seconds
  { id: 'invincibility', name: "Ghost Mode", description: "Become invincible", duration: 300 }, // 5 seconds
  { id: 'extra_jump', name: "Air Jordans", description: "Gain an extra jump", duration: 720 }, // 12 seconds
  // Add more ideas here:
  // { id: 'score_multiplier', name: "Bonus Points!", description: "Double score gain", duration: 400 },
  // { id: 'magnet', name: "Coin Magnet (if coins existed)", description: "Attracts pickups", duration: 500 },
];

// --- Theme Interface (Moved to interfaces.ts) ---
// ... (Theme interface definition removed from here) ...

// --- Define Themes ---
export const THEMES: Theme[] = [
  // Theme 0: Purple/Green
  { name: "Purple/Green", COLOR_BACKGROUND: '#300032', COLOR_BACKGROUND_GRID: 'rgba(0, 0, 0, 0.15)', COLOR_GROUND_BOTTOM: '#C800C8', COLOR_GROUND_TOP: '#FF00FF', COLOR_PLAYER_BODY: '#32CD32', COLOR_PLAYER_DETAIL: '#000000', COLOR_PLAYER_GLOW: 'rgba(173, 255, 47, 0.5)', COLOR_OBSTACLE_SPIKE: '#32CD32', COLOR_OBSTACLE_BLOCK: '#32CD32', COLOR_OBSTACLE_GEAR_OUTER: '#ADFF2F', COLOR_OBSTACLE_GEAR_INNER: '#300032', COLOR_OBSTACLE_PLATFORM: '#32CD32', COLOR_OBSTACLE_GLOW: 'rgba(173, 255, 47, 0.4)', COLOR_OBSTACLE_SAWBLADE: '#ADFF2F', COLOR_OBSTACLE_SAWBLADE_INNER: '#300032', COLOR_OBSTACLE_SAWBLADE_GLOW: 'rgba(173, 255, 47, 0.6)', COLOR_OBSTACLE_CRUSHER_BODY: '#8A2BE2', COLOR_OBSTACLE_CRUSHER_DETAIL: '#4B0082', COLOR_OBSTACLE_CRUSHER_GLOW: 'rgba(138, 43, 226, 0.5)', COLOR_OBSTACLE_LASER_BEAM: '#FF00FF', COLOR_OBSTACLE_LASER_WARNING: '#FF69B4', COLOR_OBSTACLE_LASER_GLOW: 'rgba(255, 0, 255, 0.5)', COLOR_ENEMY_BAT_BODY: '#4B0082', COLOR_ENEMY_BAT_WING: '#8A2BE2', COLOR_ENEMY_BAT_GLOW: 'rgba(138, 43, 226, 0.5)', COLOR_ENEMY_SHOOTER_BODY: '#ADFF2F', COLOR_ENEMY_SHOOTER_EYE: '#FF00FF', COLOR_ENEMY_SHOOTER_GLOW: 'rgba(173, 255, 47, 0.5)', COLOR_ENV_FIRE1: '#FF4500', COLOR_ENV_FIRE2: '#FFA500', COLOR_ENV_LAVA1: '#FF4500', COLOR_ENV_LAVA2: '#FFA500', COLOR_ENV_LAVA_GLOW: 'rgba(255, 69, 0, 0.4)', COLOR_ENV_WATERFALL1: '#00BFFF', COLOR_ENV_WATERFALL2: '#87CEEB', COLOR_ENV_WATERFALL_SPRAY: 'rgba(240, 248, 255, 0.6)', COLOR_ENV_RAIN: '#ADD8E6', COLOR_ENV_CLOUD: '#F5F5F5', COLOR_ENEMY_COW_BODY: '#D2B48C', COLOR_ENEMY_COW_SPOTS: '#8B4513', COLOR_ENEMY_COW_GLOW: 'rgba(210, 180, 140, 0.3)', COLOR_LETTER_BG: '#200022', COLOR_LETTER_BORDER: '#FF00FF', COLOR_LETTER_TEXT: '#FFFFFF', COLOR_LETTER_SENDER: '#ADFF2F', COLOR_LETTER_X: '#FF00FF', COLOR_UI_SCORE_TEXT: '#FFFFFF', COLOR_UI_SCORE_SHADOW: '#C800C8', COLOR_UI_MESSAGE_TEXT: '#ADFF2F', COLOR_UI_GAMEOVER_TEXT: '#FF00FF', COLOR_UI_GAMEOVER_BORDER: '#C800C8', COLOR_UI_GAMEOVER_SHADOW: '#FF00FF', COLOR_UI_BONUS_BG: '#200022', COLOR_UI_BONUS_BORDER: '#FF00FF', COLOR_UI_BONUS_TEXT: '#FFFFFF', COLOR_UI_BONUS_NAME: '#ADFF2F', COLOR_UI_BONUS_DESC: '#E0E0E0', COLOR_UI_BONUS_SELECTED_BG: '#400044', },
  // Theme 1: Blue/Orange
  { name: "Blue/Orange", COLOR_BACKGROUND: '#001a3a', COLOR_BACKGROUND_GRID: 'rgba(255, 255, 255, 0.08)', COLOR_GROUND_BOTTOM: '#0050a0', COLOR_GROUND_TOP: '#007FFF', COLOR_PLAYER_BODY: '#FFA500', COLOR_PLAYER_DETAIL: '#000000', COLOR_PLAYER_GLOW: 'rgba(255, 165, 0, 0.5)', COLOR_OBSTACLE_SPIKE: '#FFA500', COLOR_OBSTACLE_BLOCK: '#FFA500', COLOR_OBSTACLE_GEAR_OUTER: '#FFD700', COLOR_OBSTACLE_GEAR_INNER: '#001a3a', COLOR_OBSTACLE_PLATFORM: '#FFA500', COLOR_OBSTACLE_GLOW: 'rgba(255, 165, 0, 0.4)', COLOR_OBSTACLE_SAWBLADE: '#FFD700', COLOR_OBSTACLE_SAWBLADE_INNER: '#001a3a', COLOR_OBSTACLE_SAWBLADE_GLOW: 'rgba(255, 215, 0, 0.6)', COLOR_OBSTACLE_CRUSHER_BODY: '#4682B4', COLOR_OBSTACLE_CRUSHER_DETAIL: '#2F4F4F', COLOR_OBSTACLE_CRUSHER_GLOW: 'rgba(70, 130, 180, 0.5)', COLOR_OBSTACLE_LASER_BEAM: '#00FFFF', COLOR_OBSTACLE_LASER_WARNING: '#AFEEEE', COLOR_OBSTACLE_LASER_GLOW: 'rgba(0, 255, 255, 0.5)', COLOR_ENEMY_BAT_BODY: '#4682B4', COLOR_ENEMY_BAT_WING: '#87CEEB', COLOR_ENEMY_BAT_GLOW: 'rgba(135, 206, 235, 0.5)', COLOR_ENEMY_SHOOTER_BODY: '#FFD700', COLOR_ENEMY_SHOOTER_EYE: '#007FFF', COLOR_ENEMY_SHOOTER_GLOW: 'rgba(255, 215, 0, 0.5)', COLOR_ENV_FIRE1: '#DC143C', COLOR_ENV_FIRE2: '#FF4500', COLOR_ENV_LAVA1: '#FF6347', COLOR_ENV_LAVA2: '#FF4500', COLOR_ENV_LAVA_GLOW: 'rgba(255, 0, 0, 0.4)', COLOR_ENV_WATERFALL1: '#6495ED', COLOR_ENV_WATERFALL2: '#ADD8E6', COLOR_ENV_WATERFALL_SPRAY: 'rgba(240, 248, 255, 0.6)', COLOR_ENV_RAIN: '#B0C4DE', COLOR_ENV_CLOUD: '#E6E6FA', COLOR_ENEMY_COW_BODY: '#E0FFFF', COLOR_ENEMY_COW_SPOTS: '#4682B4', COLOR_ENEMY_COW_GLOW: 'rgba(224, 255, 255, 0.3)', COLOR_LETTER_BG: '#001025', COLOR_LETTER_BORDER: '#007FFF', COLOR_LETTER_TEXT: '#FFFFFF', COLOR_LETTER_SENDER: '#FFD700', COLOR_LETTER_X: '#FFA500', COLOR_UI_SCORE_TEXT: '#FFFFFF', COLOR_UI_SCORE_SHADOW: '#0050a0', COLOR_UI_MESSAGE_TEXT: '#FFD700', COLOR_UI_GAMEOVER_TEXT: '#FFA500', COLOR_UI_GAMEOVER_BORDER: '#0050a0', COLOR_UI_GAMEOVER_SHADOW: '#FFA500', COLOR_UI_BONUS_BG: '#001025', COLOR_UI_BONUS_BORDER: '#007FFF', COLOR_UI_BONUS_TEXT: '#FFFFFF', COLOR_UI_BONUS_NAME: '#FFD700', COLOR_UI_BONUS_DESC: '#E0E0E0', COLOR_UI_BONUS_SELECTED_BG: '#002045', },
  // Theme 2: Red/Cyan
  { name: "Red/Cyan", COLOR_BACKGROUND: '#2a0000', COLOR_BACKGROUND_GRID: 'rgba(255, 255, 255, 0.08)', COLOR_GROUND_BOTTOM: '#a00000', COLOR_GROUND_TOP: '#ff0000', COLOR_PLAYER_BODY: '#00FFFF', COLOR_PLAYER_DETAIL: '#000000', COLOR_PLAYER_GLOW: 'rgba(0, 255, 255, 0.5)', COLOR_OBSTACLE_SPIKE: '#00FFFF', COLOR_OBSTACLE_BLOCK: '#00FFFF', COLOR_OBSTACLE_GEAR_OUTER: '#7FFFD4', COLOR_OBSTACLE_GEAR_INNER: '#2a0000', COLOR_OBSTACLE_PLATFORM: '#00FFFF', COLOR_OBSTACLE_GLOW: 'rgba(0, 255, 255, 0.4)', COLOR_OBSTACLE_SAWBLADE: '#7FFFD4', COLOR_OBSTACLE_SAWBLADE_INNER: '#2a0000', COLOR_OBSTACLE_SAWBLADE_GLOW: 'rgba(127, 255, 212, 0.6)', COLOR_OBSTACLE_CRUSHER_BODY: '#DC143C', COLOR_OBSTACLE_CRUSHER_DETAIL: '#8B0000', COLOR_OBSTACLE_CRUSHER_GLOW: 'rgba(220, 20, 60, 0.5)', COLOR_OBSTACLE_LASER_BEAM: '#FFFF00', COLOR_OBSTACLE_LASER_WARNING: '#FFFACD', COLOR_OBSTACLE_LASER_GLOW: 'rgba(255, 255, 0, 0.5)', COLOR_ENEMY_BAT_BODY: '#DC143C', COLOR_ENEMY_BAT_WING: '#FF69B4', COLOR_ENEMY_BAT_GLOW: 'rgba(255, 105, 180, 0.5)', COLOR_ENEMY_SHOOTER_BODY: '#7FFFD4', COLOR_ENEMY_SHOOTER_EYE: '#FF0000', COLOR_ENEMY_SHOOTER_GLOW: 'rgba(127, 255, 212, 0.5)', COLOR_ENV_FIRE1: '#FF8C00', COLOR_ENV_FIRE2: '#FFD700', COLOR_ENV_LAVA1: '#FF8C00', COLOR_ENV_LAVA2: '#FFD700', COLOR_ENV_LAVA_GLOW: 'rgba(255, 140, 0, 0.5)', COLOR_ENV_WATERFALL1: '#40E0D0', COLOR_ENV_WATERFALL2: '#AFEEEE', COLOR_ENV_WATERFALL_SPRAY: 'rgba(240, 255, 255, 0.6)', COLOR_ENV_RAIN: '#AFEEEE', COLOR_ENV_CLOUD: '#F0FFFF', COLOR_ENEMY_COW_BODY: '#FFC0CB', COLOR_ENEMY_COW_SPOTS: '#8B0000', COLOR_ENEMY_COW_GLOW: 'rgba(255, 192, 203, 0.3)', COLOR_LETTER_BG: '#1a0000', COLOR_LETTER_BORDER: '#ff0000', COLOR_LETTER_TEXT: '#FFFFFF', COLOR_LETTER_SENDER: '#7FFFD4', COLOR_LETTER_X: '#00FFFF', COLOR_UI_SCORE_TEXT: '#FFFFFF', COLOR_UI_SCORE_SHADOW: '#a00000', COLOR_UI_MESSAGE_TEXT: '#7FFFD4', COLOR_UI_GAMEOVER_TEXT: '#00FFFF', COLOR_UI_GAMEOVER_BORDER: '#a00000', COLOR_UI_GAMEOVER_SHADOW: '#00FFFF', COLOR_UI_BONUS_BG: '#1a0000', COLOR_UI_BONUS_BORDER: '#ff0000', COLOR_UI_BONUS_TEXT: '#FFFFFF', COLOR_UI_BONUS_NAME: '#7FFFD4', COLOR_UI_BONUS_DESC: '#E0E0E0', COLOR_UI_BONUS_SELECTED_BG: '#3a0000', },
  // Theme 3: Fiery Red
  { name: "Fiery Red", COLOR_BACKGROUND: '#4d0000', COLOR_BACKGROUND_GRAD_STOP: '#8b0000', COLOR_BACKGROUND_GRID: 'rgba(255, 165, 0, 0.1)', COLOR_GROUND_BOTTOM: '#FF4500', COLOR_GROUND_TOP: '#FFA500', COLOR_PLAYER_BODY: '#32CD32', COLOR_PLAYER_DETAIL: '#000000', COLOR_PLAYER_GLOW: 'rgba(173, 255, 47, 0.5)', COLOR_OBSTACLE_SPIKE: '#00FFFF', COLOR_OBSTACLE_BLOCK: '#00FFFF', COLOR_OBSTACLE_GEAR_OUTER: '#7FFFD4', COLOR_OBSTACLE_GEAR_INNER: '#4d0000', COLOR_OBSTACLE_PLATFORM: '#FFA500', COLOR_OBSTACLE_GLOW: 'rgba(0, 255, 255, 0.4)', COLOR_OBSTACLE_SAWBLADE: '#FFFF00', COLOR_OBSTACLE_SAWBLADE_INNER: '#4d0000', COLOR_OBSTACLE_SAWBLADE_GLOW: 'rgba(255, 255, 0, 0.6)', COLOR_OBSTACLE_CRUSHER_BODY: '#A0522D', COLOR_OBSTACLE_CRUSHER_DETAIL: '#8B4513', COLOR_OBSTACLE_CRUSHER_GLOW: 'rgba(160, 82, 45, 0.5)', COLOR_OBSTACLE_LASER_BEAM: '#FF4500', COLOR_OBSTACLE_LASER_WARNING: '#FFDAB9', COLOR_OBSTACLE_LASER_GLOW: 'rgba(255, 69, 0, 0.5)', COLOR_ENEMY_BAT_BODY: '#2F4F4F', COLOR_ENEMY_BAT_WING: '#708090', COLOR_ENEMY_BAT_GLOW: 'rgba(112, 128, 144, 0.5)', COLOR_ENEMY_SHOOTER_BODY: '#00FFFF', COLOR_ENEMY_SHOOTER_EYE: '#FF4500', COLOR_ENEMY_SHOOTER_GLOW: 'rgba(0, 255, 255, 0.5)', COLOR_ENV_FIRE1: '#FF8C00', COLOR_ENV_FIRE2: '#FFD700', COLOR_ENV_LAVA1: '#FF6347', COLOR_ENV_LAVA2: '#FF8C00', COLOR_ENV_LAVA_GLOW: 'rgba(255, 100, 0, 0.6)', COLOR_ENV_WATERFALL1: '#FF4500', COLOR_ENV_WATERFALL2: '#FFA500', COLOR_ENV_WATERFALL_SPRAY: 'rgba(255, 165, 0, 0.4)', COLOR_ENV_RAIN: '#FFDEAD', COLOR_ENV_CLOUD: '#FFE4B5', COLOR_ENEMY_COW_BODY: '#A0522D', COLOR_ENEMY_COW_SPOTS: '#000000', COLOR_ENEMY_COW_GLOW: 'rgba(160, 82, 45, 0.3)', COLOR_LETTER_BG: '#2a0000', COLOR_LETTER_BORDER: '#FF4500', COLOR_LETTER_TEXT: '#FFFFFF', COLOR_LETTER_SENDER: '#FFFF00', COLOR_LETTER_X: '#00FFFF', COLOR_UI_SCORE_TEXT: '#FFFFFF', COLOR_UI_SCORE_SHADOW: '#FF4500', COLOR_UI_MESSAGE_TEXT: '#FFFF00', COLOR_UI_GAMEOVER_TEXT: '#00FFFF', COLOR_UI_GAMEOVER_BORDER: '#FF4500', COLOR_UI_GAMEOVER_SHADOW: '#00FFFF', COLOR_UI_BONUS_BG: '#2a0000', COLOR_UI_BONUS_BORDER: '#FF4500', COLOR_UI_BONUS_TEXT: '#FFFFFF', COLOR_UI_BONUS_NAME: '#FFFF00', COLOR_UI_BONUS_DESC: '#E0E0E0', COLOR_UI_BONUS_SELECTED_BG: '#4a0000', },
  // Theme 4: Lush Green
  { name: "Lush Green", COLOR_BACKGROUND: '#2E8B57', COLOR_BACKGROUND_GRAD_STOP: '#8FBC8F', COLOR_BACKGROUND_GRID: 'rgba(255, 255, 255, 0.1)', COLOR_GROUND_BOTTOM: '#556B2F', COLOR_GROUND_TOP: '#8FBC8F', COLOR_GROUND_GRASS: '#90EE90', COLOR_PLAYER_BODY: '#FF69B4', COLOR_PLAYER_DETAIL: '#000000', COLOR_PLAYER_GLOW: 'rgba(255, 105, 180, 0.5)', COLOR_OBSTACLE_SPIKE: '#DAA520', COLOR_OBSTACLE_BLOCK: '#CD853F', COLOR_OBSTACLE_GEAR_OUTER: '#DEB887', COLOR_OBSTACLE_GEAR_INNER: '#556B2F', COLOR_OBSTACLE_PLATFORM: '#CD853F', COLOR_OBSTACLE_GLOW: 'rgba(218, 165, 32, 0.4)', COLOR_OBSTACLE_SAWBLADE: '#DEB887', COLOR_OBSTACLE_SAWBLADE_INNER: '#556B2F', COLOR_OBSTACLE_SAWBLADE_GLOW: 'rgba(222, 184, 135, 0.6)', COLOR_OBSTACLE_CRUSHER_BODY: '#8B4513', COLOR_OBSTACLE_CRUSHER_DETAIL: '#556B2F', COLOR_OBSTACLE_CRUSHER_GLOW: 'rgba(139, 69, 19, 0.5)', COLOR_OBSTACLE_LASER_BEAM: '#ADFF2F', COLOR_OBSTACLE_LASER_WARNING: '#F5FFFA', COLOR_OBSTACLE_LASER_GLOW: 'rgba(173, 255, 47, 0.5)', COLOR_ENEMY_BAT_BODY: '#778899', COLOR_ENEMY_BAT_WING: '#B0C4DE', COLOR_ENEMY_BAT_GLOW: 'rgba(176, 196, 222, 0.4)', COLOR_ENEMY_SHOOTER_BODY: '#DAA520', COLOR_ENEMY_SHOOTER_EYE: '#FF69B4', COLOR_ENEMY_SHOOTER_GLOW: 'rgba(218, 165, 32, 0.5)', COLOR_ENV_FIRE1: '#90EE90', COLOR_ENV_FIRE2: '#98FB98', COLOR_ENV_LAVA1: '#A0522D', COLOR_ENV_LAVA2: '#8B4513', COLOR_ENV_LAVA_GLOW: 'rgba(139, 69, 19, 0.4)', COLOR_ENV_WATERFALL1: '#ADD8E6', COLOR_ENV_WATERFALL2: '#B0E0E6', COLOR_ENV_WATERFALL_SPRAY: 'rgba(240, 248, 255, 0.6)', COLOR_ENV_RAIN: '#98FB98', COLOR_ENV_CLOUD: '#F0FFF0', COLOR_ENEMY_COW_BODY: '#F5F5DC', COLOR_ENEMY_COW_SPOTS: '#A0522D', COLOR_ENEMY_COW_GLOW: 'rgba(245, 245, 220, 0.4)', COLOR_LETTER_BG: '#466d36', COLOR_LETTER_BORDER: '#8FBC8F', COLOR_LETTER_TEXT: '#FFFFFF', COLOR_LETTER_SENDER: '#FF69B4', COLOR_LETTER_X: '#DAA520', COLOR_UI_SCORE_TEXT: '#FFFFFF', COLOR_UI_SCORE_SHADOW: '#556B2F', COLOR_UI_MESSAGE_TEXT: '#FF69B4', COLOR_UI_GAMEOVER_TEXT: '#FF69B4', COLOR_UI_GAMEOVER_BORDER: '#556B2F', COLOR_UI_GAMEOVER_SHADOW: '#FF69B4', COLOR_UI_BONUS_BG: '#466d36', COLOR_UI_BONUS_BORDER: '#8FBC8F', COLOR_UI_BONUS_TEXT: '#FFFFFF', COLOR_UI_BONUS_NAME: '#FF69B4', COLOR_UI_BONUS_DESC: '#E0E0E0', COLOR_UI_BONUS_SELECTED_BG: '#668d56', },
];

export const THEME_SWITCH_INTERVAL = 500; // Keep theme switch interval

// --- Difficulty Scaling ---
export const DIFFICULTY_MILESTONE = 1000; // Increase difficulty every 1000 points
export const MILESTONE_SPEED_MULTIPLIER = 1.20; // Increase speed by 20% at milestone
export const MILESTONE_SPAWN_RATE_MULTIPLIER = 0.85; // Decrease spawn interval by 15%

// Game Dimensions
export const GAME_WIDTH = 1000; export const GAME_HEIGHT = 450; export const GROUND_Y = GAME_HEIGHT - 60; export const GROUND_HEIGHT = 60; export const GROUND_LINE_THICKNESS = 5;
// Player Constants
export const PLAYER_SIZE = 35; export const PLAYER_INITIAL_X = 100; export const JUMP_VELOCITY = 15; export const GRAVITY = 0.75; export const PLAYER_ROTATION_SPEED = 0.15; export const MAX_JUMPS = 2;
export const PLAYER_TINY_SCALE = 0.75; // Scale for 'tiny_player' bonus
export const PLAYER_INVINCIBILITY_ALPHA = 0.6; // Alpha for invincible player

// --- Entity Types Enum ---
export enum EntityType {
  // Obstacles
  SPIKE, BLOCK, GEAR, PLATFORM,
  TRIPLE_SPIKE, BLOCK_STACK, FLOATING_GEAR, MOVING_PLATFORM,
  SAW_BLADE, CRUSHER, LASER_BEAM,
  // Enemies
  BAT, SHOOTER, COW,
  // Hazards
  LAVA_PIT,
  // Environment (Visual Only)
  RAIN_CLOUD,
}

// Obstacle Constants
export const SPIKE_BASE_WIDTH = 40; export const SPIKE_HEIGHT = 40;
export const BLOCK_SIZE_MIN = 40; export const BLOCK_SIZE_MAX = 60;
export const GEAR_RADIUS = 35; export const GEAR_ROTATION_SPEED = 0.05;
export const PLATFORM_HEIGHT = 20; export const PLATFORM_MIN_WIDTH = 80; export const PLATFORM_MAX_WIDTH = 200; export const PLATFORM_MIN_Y_OFFSET = 80; export const PLATFORM_MAX_Y_OFFSET = 200;
export const TRIPLE_SPIKE_SPACING = 5; export const BLOCK_STACK_COUNT_MIN = 2; export const BLOCK_STACK_COUNT_MAX = 3;
export const MOVING_PLATFORM_AMP = 50; export const MOVING_PLATFORM_FREQ = 0.03;
export const SAW_BLADE_RADIUS = 30; export const SAW_BLADE_ROTATION_SPEED = 0.15;
export const CRUSHER_WIDTH = 60; export const CRUSHER_HEIGHT = 80; export const CRUSHER_TRIGGER_DIST = 150; export const CRUSHER_SPEED = 15; export const CRUSHER_WAIT_TIME = 30;
export const LASER_BEAM_THICKNESS = 10; export const LASER_CHARGE_TIME = 60; export const LASER_ACTIVE_TIME = 30; export const LASER_COOLDOWN_TIME = 90;

// Enemy Constants
export const BAT_WIDTH = 40; export const BAT_HEIGHT = 20; export const BAT_FLAP_SPEED = 0.3; export const BAT_VERTICAL_AMP = 10; export const BAT_VERTICAL_FREQ = 0.05; export const SHOOTER_SIZE = 40; export const SHOOTER_FIRE_RATE = 120; export const SHOOTER_Y_OFFSET = 5;
export const COW_WIDTH = 60; export const COW_HEIGHT = 45; export const COW_MOVE_SPEED_FACTOR = 0.5;

// Hazard Constants
export const LAVA_PIT_MIN_WIDTH = PLAYER_SIZE * 2.5; export const LAVA_PIT_MAX_WIDTH = PLAYER_SIZE * 4; export const LAVA_BUBBLE_RATE = 0.1;
// Environment Constants
export const RAIN_CLOUD_WIDTH = 80; export const RAIN_CLOUD_HEIGHT = 40; export const RAIN_CLOUD_SPEED_FACTOR = 0.3; export const RAIN_RATE = 0.5; export const RAIN_LENGTH = 10; export const RAIN_SPEED = 15;
// General Entity Logic
export const INITIAL_SPAWN_RATE = 55; export const MIN_SPAWN_RATE = 18; // Slightly lower min spawn rate
export const SPAWN_RATE_DECREASE = 0.15; // Slightly slower gradual decrease
// Game Speed
export const INITIAL_GAME_SPEED = 7; // Start slightly slower
export const MAX_GAME_SPEED = 30; // Increase max speed
export const GAME_SPEED_INCREASE = 0.0020; // Slightly slower gradual increase
// Scoring & Messages
export const SCORE_MULTIPLIER = 0.15; export const MESSAGE_INTERVAL = 350; export const REWARD_MESSAGES = [ "Just Warming Up!", "Dodged!", "Air Time!", "Too Fast!", "Reflexes!", "Blazing!", "Can't Touch This!", "Godlike!", "Light Speed!", "Impossible!", ]; export const MESSAGE_DURATION = 90;
// Letter Pause
export const LETTER_PAUSE_INTERVAL = 1500; // Increase interval for letters
export const LETTER_ICON_SIZE = 60; export const LETTER_BOX_WIDTH_RATIO = 0.7; export const LETTER_BOX_HEIGHT_RATIO = 0.6; export const LETTER_BOX_PADDING = 30; export const LETTER_CLOSE_BUTTON_SIZE = 25; export const LETTER_CLOSE_BUTTON_PADDING = 15; export const LETTER_RESUME_COUNTDOWN_SECONDS = 3; export const LETTER_MESSAGES = [ { sender: "Mama", text: "Mein Schatz, denk dran, wie stolz wir auf dich sind! Jeder Schritt, den du machst, ist wunderbar. Vergiss nicht, auch mal tief durchzuatmen. Wir haben dich lieb! Pass auf dich auf." }, { sender: "Papa", text: "Hey Champion! Siehst du, wie weit du schon gekommen bist? Unglaublich! Bleib konzentriert, aber vergiss den Spaß nicht. Du schaffst das! Dein Papa glaubt an dich." }, { sender: "Amira", text: "Heeey! Rate mal, wer dir die Daumen drückt? ICH! Du bist so schnell und geschickt, echt cool! Mach weiter so, aber überanstreng dich nicht. Küsschen, deine Amira." }, { sender: "Natalia", text: "Liebling, ich sende dir ganz viel Energie! Du meisterst das mit Bravour. Denk an etwas Schönes, das gibt Kraft. Ich bin in Gedanken bei dir und feuer dich an! Alles Liebe, Natalia." }, ];
// Bonus UI Constants
export const BONUS_CHOICE_BOX_WIDTH = 200;
export const BONUS_CHOICE_BOX_HEIGHT = 100;
export const BONUS_CHOICE_PADDING = 20;
export const BONUS_CHOICE_Y_OFFSET = 150; // Y position relative to screen center
